### ISSUE TITLE
SAM3D_DepthEstimate error ?

### ISSUE THREAD

**Issue by merecesarchviz** [PozzettiAndrea/ComfyUI-SAM3DObjects#20]
@PozzettiAndrea I was trying but i got this errors when i execute the workflow, any idea?

 

SAM3D_DepthEstimate Depth estimation failed: Inference worker error: Error in call to target 'sam3d_objects.pipeline.inference_pipeline_pointmap.InferencePipelinePointMap': InstantiationException("Error in call to target 'sam3d_objects.model.backbone.tdfy_dit.models.mm_latent.Latent':\nRuntimeError('CUDA error: no kernel image is available for execution on the device\\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\\n')\nfull_key: module.generator.backbone.reverse_fn.backbone.latent_mapping.6drotation_normalized") Traceback: Traceback (most recent call last): File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 92, in _call_target return _target_(*args, **kwargs) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\vendor\sam3d_objects\model\backbone\tdfy_dit\models\mm_latent.py", line 17, in __init__ self.input_layer = nn.Linear(in_channels, model_channels) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\torch\nn\modules\linear.py", line 104, in __init__ self.reset_parameters() File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\torch\nn\modules\linear.py", line 110, in reset_parameters init.kaiming_uniform_(self.weight, a=math.sqrt(5)) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\torch\nn\init.py", line 443, in kaiming_uniform_ return torch.overrides.handle_torch_function( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\torch\overrides.py", line 1630, in handle_torch_function result = mode.__torch_function__(public_api, types, args, kwargs) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\torch\utils\_device.py", line 79, in __torch_function__ return func(*args, **kwargs) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\torch\nn\init.py", line 460, in kaiming_uniform_ return tensor.uniform_(-bound, bound, generator=generator) RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. The above exception was the direct cause of the following exception: Traceback (most recent call last): File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 92, in _call_target return _target_(*args, **kwargs) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\vendor\sam3d_objects\pipeline\inference_pipeline_pointmap.py", line 99, in __init__ super().__init__(*args, **kwargs) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\vendor\sam3d_objects\pipeline\inference_pipeline.py", line 133, in __init__ ss_generator = self.init_ss_generator( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\vendor\sam3d_objects\pipeline\inference_pipeline.py", line 313, in init_ss_generator return self.instantiate_and_load_from_pretrained( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\vendor\sam3d_objects\pipeline\inference_pipeline.py", line 269, in instantiate_and_load_from_pretrained model = instantiate(config) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate return instantiate_node( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 342, in instantiate_node value = instantiate_node( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 342, in instantiate_node value = instantiate_node( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 342, in instantiate_node value = instantiate_node( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 366, in instantiate_node cfg[key] = instantiate_node( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 347, in instantiate_node return _call_target(_target_, partial, args, kwargs, full_key) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 97, in _call_target raise InstantiationException(msg) from e hydra.errors.InstantiationException: Error in call to target 'sam3d_objects.model.backbone.tdfy_dit.models.mm_latent.Latent': RuntimeError('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n') full_key: module.generator.backbone.reverse_fn.backbone.latent_mapping.6drotation_normalized The above exception was the direct cause of the following exception: Traceback (most recent call last): File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\inference_worker.py", line 770, in run_inference model = load_model(config_path, compile_model) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\inference_worker.py", line 223, in load_model _MODEL = instantiate(config) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 226, in instantiate return instantiate_node( File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 347, in instantiate_node return _call_target(_target_, partial, args, kwargs, full_key) File "C:\AI\ComfyUI_OVI\ComfyUI\custom_nodes\ComfyUI-SAM3DObjects\_env\lib\site-packages\hydra\_internal\instantiate\_instantiate2.py", line 97, in _call_target raise InstantiationException(msg) from e hydra.errors.InstantiationException: Error in call to target 'sam3d_objects.pipeline.inference_pipeline_pointmap.InferencePipelinePointMap': InstantiationException("Error in call to target 'sam3d_objects.model.backbone.tdfy_dit.models.mm_latent.Latent':\nRuntimeError('CUDA error: no kernel image is available for execution on the device\\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\\n')\nfull_key: module.generator.backbone.reverse_fn.backbone.latent_mapping.6drotation_normalized")

<img width="2330" height="1140" alt="Image" src="https://github.com/user-attachments/assets/495d8ee3-7400-4848-a76d-30c3f7fdc651" />

**Comment by merecesarchviz** [comment]
why this dont work with the cards 50xx!?

**Comment by freelanceagent1** [comment]
> > same exact issue. please @ me if solution is found.
> > UPDT: Upgraded _env to torch 2.8.0+cu129 and torchvision 0.23.0+cu129, which ships kernels for sm_120 (I own a 5070TI)
> 
> in my case not solved! i still got the error! :S

while I fixed the same issue you had - I'm also struggling with other issues during guassian nodes which is also connected to 50 series. I'm trying out WSL now because I do not want to build pytorch from source and update all the dependencies of these nodes. 
I will get back to you if I succeed, my friend.

**Comment by merecesarchviz** [comment]
@PozzettiAndrea in my case now pass that error and i got this new one:

<img width="2431" height="1189" alt="Image" src="https://github.com/user-attachments/assets/403ae5ce-8667-490e-a4ce-01cf0cbe21a8" />

during the process in this node:

<img width="1969" height="1167" alt="Image" src="https://github.com/user-attachments/assets/c4e93edb-7976-4a2c-a23e-72e3d37ff957" />

**Comment by pookyjuice** [comment]
I had the same issue with the guassian node, everything worked up that point. It looks like the newer version of pytorch changed a default value in the torch.load function, so I was able to get past this error by adding the 'weights_only=False' kwarg to all of the torch.load declarations in inference_worker.py and io.py
  
e.g.
`pointmap = torch.load(pointmap_path, weights_only=False)`

**Comment by PozzettiAndrea** [comment]
Thank you both for the quick response and detailed reporting! Will get to it tonight

**Comment by pookyjuice** [comment]
Sorry, I might have confused you there. I had an earlier version where that one and a few others wasn't changed yet. I think the one that matters is the line with the slat_output return value, as this person mentioned: 
https://github.com/PozzettiAndrea/ComfyUI-SAM3DObjects/issues/13#issuecomment-3631579143

**Comment by merecesarchviz** [comment]
> Sorry, I might have confused you there. I had an earlier version where that one and a few others wasn't changed yet. I think the one that matters is the line with the slat_output return value, as this person mentioned: [#13 (comment)](https://github.com/PozzettiAndrea/ComfyUI-SAM3DObjects/issues/13#issuecomment-3631579143)

yeap doing this modification:

slat_output = torch.load(request.get("slat_output_path"))
to
slat_output = torch.load(request.get("slat_output_path"), weights_only=False)

now all works perfect! thks for the information about it!

**Comment by PozzettiAndrea** [comment]
Thanks to everyone for pointing the errors out and helping me fix them :) latest version should work fine. closing this issue
